# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b32c5bfca63c5669cd34813fbfd268016bad880cb3991b01e8589090e08c78aa0d027745975fea832b152451aa8d576f867c35978fa32736534a3086ada981a1

test:
  secret_key_base: e7158cdd7f2d772d2c6b77a51ae2d4d18f28314b1ea161814391e8a9c99f7063b53b709afd060daa5a675bd644472c3efff05ef31ae3ae618bcb9331a5a32c9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
